# Generated by Django - add theme field to CompanySettings

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_company_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='theme',
            field=models.CharField(
                choices=[('orange', 'Laranja e Azul (padrão)'), ('green', 'Verde e Verde-água'), ('purple', 'Roxo e Rosa')],
                default='orange',
                max_length=20,
                verbose_name='Tema de cores'
            ),
        ),
    ]
