# Generated by Django 4.2.7

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('due_date', models.DateField(verbose_name='Data de vencimento')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Em atraso'), ('cancelled', 'Cancelado')], default='pending', max_length=15, verbose_name='Status')),
                ('provider', models.CharField(blank=True, max_length=150, verbose_name='Fornecedor')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Conta a pagar',
                'verbose_name_plural': 'Contas a pagar',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='billpayable',
            index=models.Index(fields=['status'], name='payables_bi_status_0c7f07_idx'),
        ),
        migrations.AddIndex(
            model_name='billpayable',
            index=models.Index(fields=['due_date'], name='payables_bi_due_dat_a02e7e_idx'),
        ),
    ]
