# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_company_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço mensal (R$)')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Período de teste'), ('active', 'Ativo'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='trial', max_length=20, verbose_name='Status')),
                ('trial_start', models.DateField(blank=True, null=True, verbose_name='Início do trial')),
                ('trial_end', models.DateField(blank=True, null=True, verbose_name='Fim do trial')),
                ('current_period_start', models.DateField(blank=True, null=True, verbose_name='Início do período atual')),
                ('current_period_end', models.DateField(blank=True, null=True, verbose_name='Fim do período atual')),
                ('mp_preference_id', models.CharField(blank=True, max_length=100, verbose_name='ID preferência MP')),
                ('mp_payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID pagamento MP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='users.companysettings', verbose_name='Empresa')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscription.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
    ]
