# Generated by Django 4.2.7 on 2026-01-30 23:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_stock_smart_pricing_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(max_length=44, unique=True, verbose_name='Chave de Acesso')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='nfe/xml/', verbose_name='Arquivo XML')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor (emitente)')),
                ('nfe_number', models.CharField(blank=True, max_length=20, verbose_name='Número NF-e')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfe_imports', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
            ],
            options={
                'verbose_name': 'Importação NF-e',
                'verbose_name_plural': 'Importações NF-e',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='NFeImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nome do produto (xProd)')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade')),
                ('unit', models.CharField(default='UN', max_length=10, verbose_name='Unidade')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo unitário')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo total')),
                ('gtin', models.CharField(blank=True, max_length=14, null=True, verbose_name='GTIN/EAN (cEAN)')),
                ('nfe_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='integrations.nfeimport', verbose_name='Importação NF-e')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfe_import_items', to='products.product', verbose_name='Produto vinculado')),
            ],
            options={
                'verbose_name': 'Item da Importação NF-e',
                'verbose_name_plural': 'Itens da Importação NF-e',
                'ordering': ['id'],
            },
        ),
    ]
