# Generated by Django 4.2.7 on 2025-12-22 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='sales.sale', verbose_name='Venda'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sales.sale', verbose_name='Venda'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['client'], name='sales_sale_client__5e5925_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='sales_sale_sale_da_2fd927_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='sales_sale_status_532843_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_method'], name='sales_sale_payment_7823e1_idx'),
        ),
    ]
