# Generated by Django 4.2.7 on 2025-12-22 15:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('species', models.CharField(choices=[('dog', 'Cão'), ('cat', 'Gato'), ('bird', 'Ave'), ('fish', 'Peixe'), ('reptile', 'Réptil'), ('rodent', 'Roedor'), ('other', 'Outro')], max_length=10, verbose_name='Espécie')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Raça')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Peso (kg)')),
                ('sex', models.CharField(choices=[('male', 'Macho'), ('female', 'Fêmea'), ('unknown', 'Não informado')], default='unknown', max_length=10, verbose_name='Sexo')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['-created_at'],
            },
        ),
    ]
