# Generated by Django 4.2.7 on 2025-12-22 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pets', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['client'], name='pets_pet_client__16ddb8_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['species'], name='pets_pet_species_f91a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['is_active'], name='pets_pet_is_acti_515ea0_idx'),
        ),
    ]
